general:
    verbosity: 2
paths:
    dataset_path: "data/raw/dataset.csv"
    rankings_path: "data/raw/rankings.csv"
    graph_path: "data/raw/graph.adjlist"
    train_data_path: "data/raw/dataset_train.csv"
    train_rank_data_path: "data/raw/dataset_rank_train.csv"
    test_values_path: "data/raw/X_test.csv"
    result_path: "data/predictions/regression_targaryen_prediction.csv"
    dataset_meta_information_path: "data/preprocessed/dataset_agg.csv"
    embeddings_path: "data/preprocessed/embeddings.csv"
feature_engineering:
    features_to_ohe: ["model", "tuning", "scoring"]
    poincare_embedding:
        dim: 18
        epochs: 5000
        explode_dim: True
        dim_reduction: None
    dataset_meta_information:
        nan_threshold: 0.5
        replacing_strategy: "median"
    normalize:
        method: "minmax"
data_cleaning:
    pearson_correlation:
        threshold: 0.7
modelling:
    model: "ExtraTreesClassifier"
    k_fold: 5
    hyperparam_grid: None
    split_size: 0.2

