general:
    verbosity: 1
paths:
    dataset_path: "data/raw/dataset.csv"
    rankings_path: "data/raw/rankings.csv"
    graph_path: "data/raw/graph.adjlist"
    train_data_path: "data/raw/dataset_train.csv"
    test_values_path: "data/raw/X_test.csv"
    result_path: "data/predictions/regression_targaryen_prediction.csv"
feature_engineering:
    features_to_ohe: ["model", "tuning", "scoring"]
modelling:
    model: "Dummy"
    scoring: ["neg_mean_squared_error", "r2"]
    k_fold: 5
    hyperparam_grid: None
    split_size: 0.2

